# welcome to my world 

In [5]:
import numpy as np

### Creating arrays from list

In [6]:
## Create a 1D and 2D numpy array
## numpy takes only one array as argument but that array can be multi-dimensional
## And since it's an arry, all elements must be of the same data type
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### Creating array form scratch

In [ ]:
zeros = np.zeros((3, 4))
print("Array of Zeros:\n", zeros)

ones = np.ones((2, 5))
print("Array of Ones:\n", ones)

full = np.full((3,3),5)
print("full arrays: \n",full)

random = np.random.random((2,3))
print("random:\n", random)

sequence = np.arange(0,10,2)
print("sequence: \n",sequence)


Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array of Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full arrays: 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
random:
 [[0.39715776 0.52149263 0.65628547]
 [0.41182238 0.94947368 0.50940475]]
sequence: 
 [0 2 4 6 8]


## Vector ,Matrix and Tensor

In [14]:
vector = np.array([1,2,3])
print("vector: \n",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix:\n",matrix)

Tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print("tensor:\n",Tensor)


vector: 
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape: \n", arr.shape)
print("size: \n",arr.size)
print("dimension: \n",arr.ndim)
print("datatype:\n",arr.dtype)

shape: 
 (2, 3)
size: 
 6
dimension: 
 2
datatype:
 int64


## Array Reshaping:

In [20]:
arr = np.arange(12)
print("Original array:\n",arr)

reshaped = arr.reshape((3,4))
print("reshaped array:\n",reshaped)

flattened = reshaped.flatten()
print("flattened array:\n",flattened)

reveled = flattened.ravel()
print("reveled array:\n",reveled)

Transpose = reshaped.T
print("Transposed array:\n",Transpose)



Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
