In [4]:
import numpy as np

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic slicing:", arr[2:8])          # Elements from index 2 to 7
print("with step:", arr[2:8:2])
print("negative slicing:", arr[-3])

Basic slicing: [2 3 4 5 6 7]
with step: [2 4 6]
negative slicing: 8


### filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10]


# filter with mask

In [7]:
mask = numbers > 5
greater_than_five = numbers[mask]
print("Numbers greater than 5:", greater_than_five)


Numbers greater than 5: [ 6  7  8  9 10]


## fancy indexing vs np.where

In [8]:
indices = [1, 3, 5, 7]
selected_elements = numbers[indices]
print("Selected elements at indices [1, 3, 5, 7]:", selected_elements)  
# Output: Selected elements at indices [1, 3, 5, 7]: [2 4 6 8]

where_result = np.where(numbers > 5)
print("Indices where numbers > 5:", numbers[where_result])


Selected elements at indices [1, 3, 5, 7]: [2 4 6 8]
Indices where numbers > 5: [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5, True, False)
print("Condition array (numbers > 5):", condition_array)

Condition array (numbers > 5): [False False False False False  True  True  True  True  True]


## Merging two arrays

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
concatenated = np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated)  # Output: Concatenated array:

Concatenated array: [1 2 3 4 5 6]


## Array compatibility 

In [ ]:
arr3 = np.array([7,8,9,10])
print("compatibility check:", arr1.shape == arr3.shape)


compatibility check: False


## Adding new row or column

In [13]:
arr4 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([7,8,9])
with_new_row = np.vstack((arr4, arr2))
print("Array with new row:", with_new_row)

with_new_column = np.column_stack((arr4, np.array([10,11])))
print("Array with new column:", with_new_column)


Array with new row: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with new column: [[ 1  2  3 10]
 [ 4  5  6 11]]


## Deleting a element in an array or matrix

In [14]:
arr2 = np.array([7,8,9])
deleted = np.delete(arr2, 1)  # Delete element at index 1
print("Array after deletion:", deleted)  # Output: Array after deletion: [7 9]

Array after deletion: [7 9]
